import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import SmoothScroll from "@/components/SmoothScroll";

const font = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "SoobaTech ~ Digital Çözüm Atölyesi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${font.variable} ${font.variable} h-full antialiased`}
    >

      <body suppressHydrationWarning className={`${font.className} flex flex-col`}>
        <Navbar />
        <main className="">
          <SmoothScroll>
            {children}

          </SmoothScroll>
        </main>
      </body>
    </html>
  );
}
